env:
  es6: true
  node: true
extends: 'eslint:recommended'
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins: ["@typescript-eslint"]
rules:
  camelcase: error
  indent:
    - error
    - "tab"
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always